import os

USTC_PASSPORT_USERNAME = os.environ["USTC_PASSPORT_USERNAME"]
USTC_PASSPORT_PASSWORD = os.environ["USTC_PASSPORT_PASSWORD"]
USTC_PASSPORT_FINGERPRINT = os.environ["USTC_PASSPORT_FINGERPRINT"]
USTC_PASSPORT_DEVICE_ID = os.environ["USTC_PASSPORT_DEVICE_ID"]